#! /bin/bash

set -e
cd /afs/cern.ch/work/y/yanchu/graviton/CMSSW_7_6_3_patch2/src/CMGTools/XZZ2l2nu/tools/LeptonIDEff
eval `scramv1 runtime -sh`
if [ -n "$1" ]
then
    mkdir -p rootfiles/$1
    mkdir -p plots/$1
fi
if ([ -z "$2" ]||[ "$2" == "data" ]||[[ "$2" == "-"* ]])&&[ "$2" != "-data" ]
then 
    echo '== reading data info'
    ./storehist_mee.exe config/$1/storehist_mee.config.npnm_pt_data_mu_set >/dev/null &
fi
if ([ -z "$2" ]||[ "$2" == "mcgen" ]||[[ "$2" == "-"* ]])&&[ "$2" != "-mcgen" ]
then 
    echo '== reading MC gen info'
    ./storehist_fullmc.exe config/$1/storehist_fullmc.config.pt_npnm_full_mu_set >/dev/null &
fi
if ([ -z "$2" ]||[ "$2" == "mc" ]||[[ "$2" == "-"* ]])&&[ "$2" != "-mc" ]
then
    echo '== reading MC info'
    ./storehist_mee.exe config/$1/storehist_mee.config.npnm_pt_mc_mu_set >/dev/null &
fi
if ([ -z "$2" ]||[ "$2" == "sgnl" ]||[[ "$2" == "-"* ]])&&[ "$2" != "-sgnl" ]
then
    echo '== reading signal info'
    ./storehist_mee.exe config/$1/storehist_mee.config.npnm_pt_sgnl_mu_set >/dev/null &
fi
if ([ -z "$2" ]||[ "$2" == "bkgd" ]||[[ "$2" == "-"* ]])&&[ "$2" != "-bkgd" ]
then
    echo '== reading background info'
    ./storehist_mee.exe config/$1/storehist_mee.config.npnm_pt_bkgd_mu_set >/dev/null &
fi
wait
echo '== fitting data'
./fiteff_mee_keys.exe config/$1/fiteff_mee.config.pt_data_npnm_mu_set >/dev/null &
echo '== fitting MC'
./fiteff_mee_keys.exe config/$1/fiteff_mee.config.pt_mc_npnm_mu_set >/dev/null &
wait
echo '== Calculating efficiencies and SF'
root -l -b -q "macros/make_effratio_npnm_mu_set.C(\"$1\")" >/dev/null